### PR TITLE
Russian changes to TIR

### PR DESCRIPTION
**Pull request by Bolgarev**
# Description
1. add def ClickComboBox
Clicks on a Label in ComboBox on the screen.
Added due to the fact that the SetValue does not work in the web interface of the national platform.

2. add def Randomex 
Method that return random digits of number.
Added for easier random number generation in tests.

3. add def FindButton
Method that gets string label of button from %name_module%.tres files.
Added to increase the stability of the tests. In particular, this allows you to write tests for the system in any localization (English, Russian, etc.)

4. add GiveMeAccess
Call of the function give to your instance (ex. inst_1) which is copy of WebApp class instance. (__webapp), private methods from WebappInternal class.

5. add some stuff in language.py cause of troubles with Russian localization.

6. add some stuff in log.py cause cause of troubles with Russian localization

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual
- [ ] SmartTest

We tested all these changes on our localized environment (ma-3).
As a result of the localization of Proteus in MA-3, the web interface has also changed.
Much of what works in Protheus and TIR is not applicable for MA-3.

I will give you our test cases, but I'm not sure that they will help you, because they work, only in MA-3.
I suggest that you organize in your repository the Russian localization branch, where only Russian changes will be posted, and update it together with the master branch.

[russianTestCases.zip](https://github.com/totvs/tir/files/3506315/russianTestCases.zip)

### CODE REVIEW

**Comment by renanllisboa** [comment]
Hi Bolgarev, first of all we need separate this features and hotfixes in various PR, but i have some questions and sugestions in quote, to simplify see the list below:

add def ClickComboBox
Clicks on a Label in ComboBox on the screen.
Added due to the fact that the SetValue does not work in the web interface of the national platform.
> We can fill this kind of field only using SetValue method, please let us know why this implementation is necessary for you and we can fix the SetValue together. 

add def Randomex
Method that return random digits of number.
Added for easier random number generation in tests.
> This is an example of implementation that must be separate, but is necessary a test script example using this method to validate. **Pull Request will still be evaluated**

add def FindButton
Method that gets string label of button from %name_module%.tres files.
Added to increase the stability of the tests. In particular, this allows you to write tests for the system in any localization (English, Russian, etc.)
> This is an example of implementation that must be separate, but is necessary a test script example using this method to validate. **Pull Request will still be evaluated**

add GiveMeAccess
Call of the function give to your instance (ex. inst_1) which is copy of WebApp class instance. (__webapp), private methods from WebappInternal class.
> The main class is necessary to limit and simplify the methods in a high level, in case of necessity we prefer create a high level method with this implementation.

add some stuff in language.py cause of troubles with Russian localization.
> This is an example of implementation that must be separate, but is necessary a test script example using this method to validate. **Pull Request will still be evaluated**

add some stuff in log.py cause cause of troubles with Russian localization
> Encode must be a parameter, we can fix this in the next releases.
> This is an example of implementation that must be separate, but is necessary a test script example using this method to validate. **Pull Request will still be evaluated**

**Comment by Bolgarev** [comment]
@renanllisboa Do you want me to split requests for changing functionality and introducing new functionality? Is this critical?

Below my team justifies the implementation of the changes. Examine the rationale.
To get examples, use the archive with test cases, which I attached to the pull request earlier.

**1) def GiveMeAccess()**

Function solves out calling class WebappInternal [Internal] methods. In some cases ( MATA632(grid with many strings, where SetValue must work, but no), MATA712(in menu, where ClickIcon or ClickLabel must work), MATA101N(), MATA121(grid, where SetValue must work) ) we need to use Selenium methods ( .click(), send_keys() etc.), ActionChains methods ( double_click(), move_to_element() etc.) and of cause we need to send ActionChains the current webdriver of browser. For making our tests work.

**2) def ClickComboBox()**

Solves the problem of clicking on combobox without the id name like - [C2_PRODUTO, CCONDICAO, etc..] in the MATA455 we got the comboBox like on the attached screenshot (mata455_ComboBox + mata455_ComboBox_develop) and SetButton/SetValue/... need to get parameter of id to pass the value in box (in db exactly), so we need to find it on the screen by get_current_container internal method, extract the values, than click by Selenium on required value.

mata455_ComboBox_develop
mata455_ComboBox

3) We don't need to make upper-level methods in main.py, cause simply we may use the "descriptor" like:
[In test]
<descriptor_1 = self.oHelper.GiveMeAccess()>
<descriptor_1.wait_element()>

Instead of making excess work like tossing every [Internal] method in main.py.

**Comment by renanllisboa** [comment]
@Bolgarev, we prefer a Pull Request by functionality, that is important to check, validate more fast this approval.

Ex: Pull Request to GiveMeAccess() method with testcases examples.

PS: Don't forget to update your fork.

Regards

**Comment by Bolgarev** [comment]
Hello!
We fixed your framework and supplemented our pull-request;
[xwiki_QA_TIR_Function+Summary+(en)_WebHome.pdf](https://github.com/totvs/tir/files/3626279/xwiki_QA_TIR_Function%2BSummary%2B.en._WebHome.pdf)
see the documentation below.
Thank.

**Comment by renanllisboa** [comment]
Hi @Bolgarev,

Based on the guidelines that i mentioned above and that you can find on Contributing.md of our project, your pull request doesn't not qualified to accepted. We wait that soon you send us a pull request respecting our guideline and then we can approve it.

**Pull request closed without merging**
